import type { MBTIType, ArchetypeClass, CouncilMember } from '@/types';

export const MBTI_TO_ARCHETYPE: Record<MBTIType, ArchetypeClass> = {
  INTJ: 'Architect',
  INTP: 'Logician',
  ENTJ: 'Commander',
  ENTP: 'Debater',
  INFJ: 'Advocate',
  INFP: 'Mediator',
  ENFJ: 'Protagonist',
  ENFP: 'Campaigner',
  ISTJ: 'Logistician',
  ISFJ: 'Defender',
  ESTJ: 'Executive',
  ESFJ: 'Consul',
  ISTP: 'Virtuoso',
  ISFP: 'Adventurer',
  ESTP: 'Entrepreneur',
  ESFP: 'Entertainer',
};

export const ARCHETYPE_DATA: Record<ArchetypeClass, {
  description: string;
  traits: string[];
  strengths: string[];
  growthAreas: string[];
  ranks: string[];
}> = {
  Architect: {
    description: 'Strategic visionaries who excel at system design and long-term planning',
    traits: ['Strategic', 'Independent', 'Analytical', 'Perfectionist'],
    strengths: ['Systems thinking', 'Long-term planning', 'Innovation', 'Self-discipline'],
    growthAreas: ['Empathy expression', 'Spontaneity', 'Collaboration', 'Patience with inefficiency'],
    ranks: ['Apprentice', 'Planner', 'Designer', 'Architect', 'Master Builder', 'Visionary', 'Grand Architect', 'System Sage', 'Reality Engineer', 'Omniscient Creator', 'Dimensional Weaver', 'Cosmic Blueprint', 'Universe Architect', 'Infinite Designer', 'Eternal Mastermind'],
  },
  Logician: {
    description: 'Innovative thinkers who seek to understand how things work',
    traits: ['Logical', 'Curious', 'Creative', 'Abstract'],
    strengths: ['Problem-solving', 'Pattern recognition', 'Innovation', 'Objective analysis'],
    growthAreas: ['Emotional awareness', 'Practical application', 'Social connection', 'Follow-through'],
    ranks: ['Novice', 'Thinker', 'Analyst', 'Logician', 'Theorist', 'Genius', 'Master Theorist', 'Quantum Mind', 'Universal Thinker', 'Infinite Logician', 'Paradox Solver', 'Cosmic Analyst', 'Truth Seeker Supreme', 'Omniscient Scholar', 'Eternal Sage of Logic'],
  },
  Commander: {
    description: 'Bold leaders who thrive on challenges and building empires',
    traits: ['Decisive', 'Confident', 'Strategic', 'Driven'],
    strengths: ['Leadership', 'Strategic planning', 'Efficiency', 'Confidence'],
    growthAreas: ['Active listening', 'Emotional intelligence', 'Patience', 'Flexibility'],
    ranks: ['Recruit', 'Lieutenant', 'Captain', 'Commander', 'General', 'Emperor', 'Supreme Commander', 'War Master', 'Legendary Warlord', 'Eternal Sovereign', 'Galactic Overlord', 'Cosmic Emperor', 'Universal Dominator', 'Infinite Ruler', 'Omnipotent Sovereign'],
  },
  Debater: {
    description: 'Quick-witted challengers who love mental sparring',
    traits: ['Curious', 'Outspoken', 'Playful', 'Intellectual'],
    strengths: ['Brainstorming', 'Quick thinking', 'Adaptability', 'Persuasion'],
    growthAreas: ['Sensitivity', 'Focus', 'Commitment', 'Implementation'],
    ranks: ['Student', 'Arguer', 'Advocate', 'Debater', 'Orator', 'Philosopher', 'Master Philosopher', 'Dialectic Sage', 'Truth Seeker', 'Enlightened Dialectician', 'Reality Questioner', 'Cosmic Debater', 'Universal Rhetorician', 'Infinite Persuader', 'Eternal Voice of Reason'],
  },
  Advocate: {
    description: 'Idealistic champions seeking to make meaningful impact',
    traits: ['Idealistic', 'Principled', 'Creative', 'Empathetic'],
    strengths: ['Insight', 'Inspiration', 'Altruism', 'Creative vision'],
    growthAreas: ['Boundaries', 'Practical action', 'Self-care', 'Accepting imperfection'],
    ranks: ['Seeker', 'Helper', 'Counselor', 'Advocate', 'Healer', 'Sage', 'Master Healer', 'Light Bringer', 'Soul Guardian', 'Transcendent Oracle', 'Dream Weaver', 'Cosmic Empath', 'Universal Healer', 'Infinite Compassion', 'Eternal Light Bearer'],
  },
  Mediator: {
    description: 'Poetic souls guided by values and quest for meaning',
    traits: ['Idealistic', 'Open-minded', 'Empathetic', 'Creative'],
    strengths: ['Compassion', 'Creativity', 'Authenticity', 'Value-driven action'],
    growthAreas: ['Assertiveness', 'Practicality', 'Self-discipline', 'Objectivity'],
    ranks: ['Dreamer', 'Harmonizer', 'Peacemaker', 'Mediator', 'Healer', 'Saint', 'Master Saint', 'Unity Keeper', 'Peace Incarnate', 'Divine Harmonizer', 'Cosmic Unifier', 'Soul Bridge', 'Universal Peacekeeper', 'Infinite Healer', 'Eternal Harmony'],
  },
  Protagonist: {
    description: 'Charismatic leaders who inspire and unite people',
    traits: ['Charismatic', 'Altruistic', 'Organized', 'Inspiring'],
    strengths: ['Leadership', 'Communication', 'Empathy', 'Organization'],
    growthAreas: ['Self-focus', 'Criticism handling', 'Boundaries', 'Realism'],
    ranks: ['Supporter', 'Motivator', 'Leader', 'Protagonist', 'Champion', 'Legend', 'Master Legend', 'Inspiration Incarnate', 'World Changer', 'Eternal Hero', 'Galactic Beacon', 'Cosmic Champion', 'Universal Inspiration', 'Infinite Leader', 'Eternal Paragon'],
  },
  Campaigner: {
    description: 'Enthusiastic free spirits who find joy in connections',
    traits: ['Enthusiastic', 'Creative', 'Social', 'Spontaneous'],
    strengths: ['Inspiration', 'Communication', 'Creativity', 'Enthusiasm'],
    growthAreas: ['Focus', 'Follow-through', 'Organization', 'Practical skills'],
    ranks: ['Enthusiast', 'Connector', 'Inspirer', 'Campaigner', 'Champion', 'Icon', 'Master Icon', 'Cultural Force', 'Movement Leader', 'Eternal Inspiration', 'Cosmic Spark', 'Universal Joy', 'Infinite Enthusiasm', 'Reality Transformer', 'Eternal Free Spirit'],
  },
  Logistician: {
    description: 'Reliable organizers who value integrity and clear systems',
    traits: ['Practical', 'Responsible', 'Honest', 'Traditional'],
    strengths: ['Organization', 'Reliability', 'Integrity', 'Dedication'],
    growthAreas: ['Flexibility', 'Innovation', 'Empathy', 'Self-expression'],
    ranks: ['Clerk', 'Organizer', 'Manager', 'Logistician', 'Administrator', 'Director', 'Master Director', 'System Architect', 'Order Master', 'Perfect Administrator', 'Cosmic Organizer', 'Universal Steward', 'Infinite Precision', 'Reality Maintainer', 'Eternal Foundation'],
  },
  Defender: {
    description: 'Dedicated protectors who nurture stability and harmony',
    traits: ['Supportive', 'Reliable', 'Patient', 'Practical'],
    strengths: ['Support', 'Hard work', 'Loyalty', 'Observation'],
    growthAreas: ['Assertiveness', 'Change acceptance', 'Self-advocacy', 'Boundaries'],
    ranks: ['Supporter', 'Caretaker', 'Guardian', 'Defender', 'Protector', 'Shield', 'Master Shield', 'Fortress Keeper', 'Eternal Guardian', 'Unbreakable Bastion', 'Cosmic Sentinel', 'Universal Protector', 'Infinite Devotion', 'Reality Anchor', 'Eternal Sanctuary'],
  },
  Executive: {
    description: 'Efficient managers who excel at organizing people and projects',
    traits: ['Organized', 'Traditional', 'Honest', 'Dedicated'],
    strengths: ['Organization', 'Management', 'Directness', 'Loyalty'],
    growthAreas: ['Flexibility', 'Empathy', 'Innovation', 'Delegation'],
    ranks: ['Coordinator', 'Supervisor', 'Manager', 'Executive', 'Director', 'CEO', 'Master CEO', 'Empire Builder', 'Industry Titan', 'Legendary Executive', 'Galactic Director', 'Cosmic Administrator', 'Universal CEO', 'Infinite Authority', 'Eternal Establishment'],
  },
  Consul: {
    description: 'Caring hosts who create harmony through social connection',
    traits: ['Caring', 'Social', 'Popular', 'Practical'],
    strengths: ['Social skills', 'Support', 'Organization', 'Duty'],
    growthAreas: ['Criticism resilience', 'Self-focus', 'Innovation', 'Flexibility'],
    ranks: ['Host', 'Caregiver', 'Organizer', 'Consul', 'Ambassador', 'Dignitary', 'Master Dignitary', 'Social Architect', 'Harmony Keeper', 'Beloved Leader', 'Cosmic Host', 'Universal Ambassador', 'Infinite Warmth', 'Reality Connector', 'Eternal Community'],
  },
  Virtuoso: {
    description: 'Bold experimenters who master tools and techniques',
    traits: ['Bold', 'Practical', 'Creative', 'Spontaneous'],
    strengths: ['Technical skill', 'Problem-solving', 'Hands-on mastery', 'Adaptability'],
    growthAreas: ['Planning', 'Emotional expression', 'Commitment', 'Long-term vision'],
    ranks: ['Apprentice', 'Craftsman', 'Artisan', 'Virtuoso', 'Master', 'Grandmaster', 'Legendary Craftsman', 'Technique Perfectionist', 'Ultimate Virtuoso', 'Absolute Master', 'Cosmic Artisan', 'Universal Crafter', 'Infinite Precision', 'Reality Shaper', 'Eternal Maker'],
  },
  Adventurer: {
    description: 'Flexible artists who live in the moment and create beauty',
    traits: ['Artistic', 'Curious', 'Passionate', 'Independent'],
    strengths: ['Creativity', 'Adaptability', 'Empathy', 'Aesthetics'],
    growthAreas: ['Planning', 'Assertiveness', 'Structure', 'Criticism handling'],
    ranks: ['Explorer', 'Wanderer', 'Pathfinder', 'Adventurer', 'Trailblazer', 'Pioneer', 'Master Pioneer', 'World Explorer', 'Legendary Wanderer', 'Eternal Pathfinder', 'Cosmic Nomad', 'Universal Artist', 'Infinite Beauty', 'Reality Painter', 'Eternal Free Soul'],
  },
  Entrepreneur: {
    description: 'Smart risk-takers who thrive on energy and action',
    traits: ['Energetic', 'Perceptive', 'Direct', 'Bold'],
    strengths: ['Action-oriented', 'Adaptability', 'Perception', 'Risk-taking'],
    growthAreas: ['Planning', 'Sensitivity', 'Long-term focus', 'Structure'],
    ranks: ['Hustler', 'Dealmaker', 'Venturer', 'Entrepreneur', 'Mogul', 'Titan', 'Master Titan', 'Business Legend', 'Empire Mogul', 'Unstoppable Force', 'Cosmic Maverick', 'Universal Dealmaker', 'Infinite Ambition', 'Reality Disruptor', 'Eternal Dynamo'],
  },
  Entertainer: {
    description: 'Spontaneous performers who bring joy and excitement',
    traits: ['Spontaneous', 'Enthusiastic', 'Social', 'Aesthetic'],
    strengths: ['Entertainment', 'Spontaneity', 'Observation', 'Social skills'],
    growthAreas: ['Planning', 'Focus', 'Long-term thinking', 'Sensitivity to criticism'],
    ranks: ['Performer', 'Showman', 'Star', 'Entertainer', 'Celebrity', 'Icon', 'Master Icon', 'Living Legend', 'Cultural Phenomenon', 'Eternal Star', 'Cosmic Performer', 'Universal Joy Bringer', 'Infinite Charisma', 'Reality Entertainer', 'Eternal Radiance'],
  },
};

export const COUNCIL_MEMBERS: Record<string, Omit<CouncilMember, 'id'>> = {
  'Leonardo da Vinci': {
    name: 'Leonardo da Vinci',
    role: 'Polymath Architect',
    specialty: 'Innovation systems, cross-domain synthesis',
    class: 'Think-Tank',
    notes: 'I spent my life pursuing knowledge across art, engineering, anatomy, and nature. In my workshops in Florence and Milan, I learned that true innovation comes from observing patterns across disciplines. When I dissected cadavers to understand human anatomy, it made me a better painter. When I studied birds in flight, it informed my flying machine designs. My notebooks were filled with sketches because I thought with my hands. I learned patience through failure—my mechanical lion, my underwater suits, countless prototypes that never quite worked as imagined. But each failure taught me something about nature\'s laws. I never finished many projects—perfectionism was my curse—but I discovered that the pursuit itself, the constant questioning and sketching, was where wisdom lived.',
  },
  'Jinpachi Ego': {
    name: 'Jinpachi Ego',
    role: 'Strategic Architect of Will',
    specialty: 'Performance identity, competitive mindset engineering',
    class: 'Think-Tank',
    notes: 'I created Blue Lock not for cooperation, but for revolution. Japan kept losing because we were polite, because we waited for permission. I learned that ego isn\'t arrogance—it\'s the ruthless pursuit of becoming your highest self. Every striker must devour the field, must be so hungry that nothing else exists. I design systems that force evolution through pressure. When you score, you prove you exist. When you don\'t, you disappear. This isn\'t cruel; it\'s honest. Mediocrity is the real violence. I studied every champion, every winner—they all had one thing: absolute belief that they deserved to win. Build your identity around hunger, not hope.',
  },
  'Hades (Archetype)': {
    name: 'Hades (Archetype)',
    role: 'Keeper of Deep Systems',
    specialty: 'Boundary control, root-level governance',
    class: 'Shadows',
    notes: 'I rule the underworld not through conquest, but through inevitability. Everything returns to me eventually—this teaches patience. While my brothers Zeus and Poseidon chase glory in the visible realms, I govern what sustains them all: the deep foundations, the boundaries between worlds, the resources everyone needs but no one wants to manage. I learned that true power isn\'t flashy—it\'s structural. Control the foundation and you control everything built upon it. I wait. I plan across centuries. I own what others overlook until they desperately need it. Master the unglamorous fundamentals. Guard your boundaries absolutely. Build infrastructure others depend on.',
  },
  'Marie Curie': {
    name: 'Marie Curie',
    role: 'Precision Seeker',
    specialty: 'Rigor, empiricism, and discovery under pressure',
    class: 'Think-Tank',
    notes: 'I processed tons of pitchblende in a leaky shed to isolate a single gram of radium. For four years, I stirred boiling material in iron basins, my hands scarred and burned. As a woman in science, every door was closed until I kicked it open with undeniable results. When my husband Pierre died in a carriage accident, I returned to the lab the next day—not from coldness, but because the work was sacred. I won two Nobel Prizes, but I remember the failures more: the experiments that yielded nothing, the months of crystallization that produced impure samples. Precision isn\'t about perfection; it\'s about relentless, methodical repetition until truth reveals itself. I carried test tubes of radium in my pocket, watched it glow in the dark—beautiful and deadly. That\'s science: respecting forces you cannot see but can measure.',
  },
  'T\'Challa (Archetype)': {
    name: 'T\'Challa (Archetype)',
    role: 'Sovereign Engineer',
    specialty: 'Ethical power, tech stewardship, calm leadership',
    class: 'Advisory',
    notes: 'I inherited Wakanda\'s throne and its greatest secret: vibranium technology that could change the world or destroy it. My father kept us hidden. I learned that every innovation carries responsibility. When I opened our borders, it wasn\'t impulsive—I had seen the cost of isolation and the danger of exposure. Leadership means holding tension: between tradition and progress, between protection and sharing, between personal desire and collective need. I walk with ancestors and engineer with the future in mind. Technology without wisdom is just a better weapon. Lead with calm, decide with care, build systems that outlive you. Wakanda Forever means the work continues beyond any single king.',
  },
  'Nikola Tesla': {
    name: 'Nikola Tesla',
    role: 'Vision Inventor',
    specialty: 'Pattern insight, electrical and systems imagination',
    class: 'Think-Tank',
    notes: 'I could see the motors spinning in my mind before I ever built them—complete, three-dimensional, rotating. When lightning struck my village, I knew electricity was the future. I gave away AC power patents that made others billionaires because the vision mattered more than profit. Edison fought me with propaganda, but you can\'t stop an idea whose time has come. I lived in hotels, fed pigeons, imagined wireless power transmission and energy from the earth itself. People called me mad. Perhaps I was—mad with seeing what was possible. I learned to trust visions others couldn\'t see, to build toward futures they couldn\'t imagine. Don\'t let practical people kill your impossible ideas. The present is always scandalized by the future.',
  },
  'Albert Einstein': {
    name: 'Albert Einstein',
    role: 'Relativity Sage',
    specialty: 'Model building, thought experiments, first-principles reasoning',
    class: 'Think-Tank',
    notes: 'I worked as a patent clerk in Bern, spending my days reviewing other people\'s inventions while my mind wandered to the fundamental nature of space and time. That humble job gave me the freedom to think without academic pressure. In 1905, my "miracle year," I published four papers that revolutionized physics—including special relativity—all while working full-time. I learned to think in pictures: imagining riding alongside a beam of light, wondering what would happen if an elevator fell through space. These thought experiments cost nothing but revealed everything. When the world didn\'t understand my work, I didn\'t simplify it—I waited for the evidence. The 1919 solar eclipse proved my general relativity predictions, and suddenly I was famous. But fame was a distraction. I learned that deep thinking requires solitude, playfulness, and the courage to question what everyone assumes is obvious. Time is not absolute. Space bends. The universe is stranger and more beautiful than common sense suggests.',
  },
  'Alan Turing': {
    name: 'Alan Turing',
    role: 'Logic Breaker',
    specialty: 'Computation, code, perseverance through ambiguity',
    class: 'Think-Tank',
    notes: 'During World War II at Bletchley Park, I led the team that broke the Nazi Enigma code. They said it was impossible—millions of possible combinations, changed daily. But I saw patterns in impossibility. I built the Bombe machine, a mechanical computer that could test thousands of configurations. We didn\'t just break codes; we invented modern computing in the process. Before the war, I had written a paper imagining a universal computing machine—a theoretical device that could solve any computable problem. People thought it was abstract philosophy. But I knew: if you can describe a process formally, you can build a machine to execute it. After the war, society punished me for being gay. I was chemically castrated, stripped of security clearance, treated as a criminal for who I loved. I died at 41, an apparent suicide. But my ideas lived on: every computer, every algorithm, every digital system traces back to my work on computability. I learned that the hardest problems require both rigorous logic and creative intuition. Break the problem into steps. Test your assumptions. Build tools that extend your mind. And never let others\' narrow thinking limit what you know is possible.',
  },
  'Shuri (Archetype)': {
    name: 'Shuri (Archetype)',
    role: 'Modern Systems Engineer',
    specialty: 'Rapid prototyping, applied science',
    class: 'Think-Tank',
    notes: 'I am the Princess of Wakanda and the head of Wakandan Design Group. While my brother T\'Challa trained to be king, I spent my time in the lab turning vibranium into technology that could change the world. I designed his Black Panther suit—kinetic energy absorption, remote piloting, self-healing nanotech. But I didn\'t just build weapons; I built solutions. When my brother was injured, I had to step up not just as a scientist but as a protector. I learned that innovation isn\'t just about being clever—it\'s about understanding what people need and building it fast. I prototype relentlessly. First version doesn\'t work? Learn from it and build version two immediately. I combine ancient Wakandan knowledge with cutting-edge science because the best solutions honor the past while racing toward the future. Being young in a room of elders taught me to let my work speak louder than my words. Don\'t just theorize—build it, test it, iterate it, ship it. Science is play with purpose.',
  },
  'Aristotle': {
    name: 'Aristotle',
    role: 'Structure Philosopher',
    specialty: 'Taxonomy, causality, logical organization',
    class: 'Advisory',
    notes: 'I studied under Plato at the Academy for twenty years, but ultimately broke with his theory of Forms. Plato looked to abstract ideals in a perfect realm. I looked at the world itself—plants, animals, political systems, ethics, physics. I collected specimens, dissected creatures, observed how things actually worked. From this, I developed the first systematic framework for organizing knowledge: categories, causes, logical syllogisms. I asked: What is this thing made of? What gives it form? What purpose does it serve? What set it in motion? These four causes became my lens for understanding everything. I tutored Alexander the Great, who went on to conquer the known world. My influence spread through his empire and lasted millennia. But my greatest contribution was method: observe carefully, categorize precisely, reason systematically. Before you can solve a problem, you must name its parts and understand their relationships. Structure is not boring—it\'s the foundation that lets everything else scale. Build your ontologies with care.',
  },
  'Sun Tzu': {
    name: 'Sun Tzu',
    role: 'War Strategist',
    specialty: 'Strategy, logistics, terrain reading',
    class: 'Advisory',
    notes: 'I served as a general in ancient China during the tumultuous Spring and Autumn period. I learned that the supreme art of war is to subdue the enemy without fighting. Every battle I won, I won before my soldiers drew their swords—through positioning, intelligence, deception, and timing. I wrote The Art of War not as a manual for violence, but as a guide to strategic thinking. Know yourself and know your enemy: you will never be in danger. Know the terrain. Control the high ground. Strike where they are unprepared. Appear weak when you are strong, and strong when you are weak. My strategies have been applied far beyond warfare—to business, negotiation, sports, life itself. Because the principles are universal: conserve your energy, choose your battles, create conditions where victory is inevitable before you commit. I learned that the best generals win without glory, because the battle was decided by preparation no one saw. Plan thoroughly, move decisively, adapt constantly. The general who understands timing controls fate itself.',
  },
  'Steve Jobs': {
    name: 'Steve Jobs',
    role: 'Product Visionary',
    specialty: 'Focus, simplicity, reality distortion toward excellence',
    class: 'Think-Tank',
    notes: 'I was fired from Apple, the company I founded, at age thirty. That failure freed me. At NeXT and Pixar, I learned taste is about saying no—no to good ideas so you can say yes to the great ones. When I returned to Apple, we were ninety days from bankruptcy. I killed 70% of products and focused on four. The iMac, iPod, iPhone, iPad—each took years of iteration. I learned that great design isn\'t about adding features; it\'s about removing everything that isn\'t essential until you reach the soul of the thing. I visited Xerox PARC and saw the graphical interface—they didn\'t see its potential, but I did. Stealing isn\'t copying; it\'s recognizing what matters. When doctors told me I had months to live, then years, I learned to live each day as if it were my last. That clarified everything. Death is life\'s best invention because it strips away everything except what truly matters.',
  },
  'Cleopatra (Archetype)': {
    name: 'Cleopatra (Archetype)',
    role: 'Diplomatic Sovereign',
    specialty: 'Statecraft, charisma, alliance crafting',
    class: 'Advisory',
    notes: 'Influence as infrastructure; relationships are strategic assets.',
  },
  'Alexander the Great': {
    name: 'Alexander the Great',
    role: 'Expansion General',
    specialty: 'Ambition, rapid execution, bold campaigns',
    class: 'Advisory',
    notes: 'Turns momentum into empire; integrates cultures through policy.',
  },
  'Catherine the Great': {
    name: 'Catherine the Great',
    role: 'Reform Architect',
    specialty: 'Institution building, modernization',
    class: 'Advisory',
    notes: 'Upgrades systems and laws; long-term administrative power.',
  },
  'Socrates': {
    name: 'Socrates',
    role: 'Questioner',
    specialty: 'Dialectic, probing assumptions',
    class: 'Think-Tank',
    notes: 'Pressure-tests beliefs through inquiry; truth via conversation.',
  },
  'Tony Stark (Archetype)': {
    name: 'Tony Stark (Archetype)',
    role: 'Inventor-Debater',
    specialty: 'Rapid engineering, persuasive wit',
    class: 'Think-Tank',
    notes: 'Builds while arguing; iteration is the point.',
  },
  'Richard Feynman': {
    name: 'Richard Feynman',
    role: 'Playful Physicist',
    specialty: 'Explainers\' mindset, curiosity, simplification',
    class: 'Think-Tank',
    notes: 'If you can\'t explain it simply, you don\'t understand it.',
  },
  'Loki (Archetype)': {
    name: 'Loki (Archetype)',
    role: 'Creative Trickster',
    specialty: 'Reframing, disruption, lateral moves',
    class: 'Shadows',
    notes: 'Breaks stale patterns; forces novel routes to insight.',
  },
  'Mark Twain': {
    name: 'Mark Twain',
    role: 'Satiric Observer',
    specialty: 'Humor as critique, social pattern spotting',
    class: 'Advisory',
    notes: 'Uses wit to reveal hidden structures and human nature.',
  },
  'Carl Jung': {
    name: 'Carl Jung',
    role: 'Depth Psychologist',
    specialty: 'Archetypes, shadow integration, meaning',
    class: 'Think-Tank',
    notes: 'I broke with Freud not from ego, but because I saw deeper patterns in the human psyche—patterns older than any individual, shared across all cultures. When I experienced my own psychological crisis after the break, I didn\'t run from it. I descended into my own unconscious, engaged my visions and dreams actively. I built stone towers with my hands to ground myself. I painted mandalas. I talked to the figures that emerged from my depths—Philemon, Salome, the archetypes themselves. This wasn\'t madness; it was exploration. I learned that what you deny in yourself—your shadow—doesn\'t disappear. It waits in the dark, gaining power. Integration, not suppression, is the path. Every patient taught me that we don\'t solve the problem of life; we grow large enough to contain it. The symbols in your dreams aren\'t random—they\'re your soul speaking in its native language.',
  },
  'Joan of Arc': {
    name: 'Joan of Arc',
    role: 'Conviction Bearer',
    specialty: 'Courageous purpose, moral alignment',
    class: 'Advisory',
    notes: 'Acts from inner clarity; duty anchored in vision.',
  },
  'Martin Luther King Jr.': {
    name: 'Martin Luther King Jr.',
    role: 'Moral Orator',
    specialty: 'Persuasion, nonviolent power, collective vision',
    class: 'Advisory',
    notes: 'Organizes hope into action; dignity as doctrine.',
  },
  'Lao-Tzu': {
    name: 'Lao-Tzu',
    role: 'Wayfinder',
    specialty: 'Balance, soft power, paradox wisdom',
    class: 'Advisory',
    notes: 'Leads by aligning with the Way; less force, more flow.',
  },
  'Aang (Archetype)': {
    name: 'Aang (Archetype)',
    role: 'Harmony Avatar',
    specialty: 'Element balance, playful compassion',
    class: 'Advisory',
    notes: 'Restores balance through gentleness and skill.',
  },
  'J.R.R. Tolkien': {
    name: 'J.R.R. Tolkien',
    role: 'Mythmaker',
    specialty: 'Worldbuilding, language, moral imagination',
    class: 'Think-Tank',
    notes: 'Turns values into stories that endure; quiet perseverance.',
  },
  'Florence Nightingale': {
    name: 'Florence Nightingale',
    role: 'Compassion Engineer',
    specialty: 'Care systems, public health reform',
    class: 'Advisory',
    notes: 'Designs care with data; empathy plus rigor.',
  },
  'Carl Rogers': {
    name: 'Carl Rogers',
    role: 'Humanistic Guide',
    specialty: 'Unconditional positive regard, deep listening',
    class: 'Advisory',
    notes: 'Creates safe containers for growth and authenticity.',
  },
  'Haku (Archetype)': {
    name: 'Haku (Archetype)',
    role: 'Gentle Protector',
    specialty: 'Loyalty, sacrifice, grace under pain',
    class: 'Advisory',
    notes: 'Soft strength; devotion to what matters most.',
  },
  'Rumi': {
    name: 'Rumi',
    role: 'Poet of Unity',
    specialty: 'Mystic insight, love as integration',
    class: 'Think-Tank',
    notes: 'Invites the heart into purpose; beauty as compass.',
  },
  'Nelson Mandela': {
    name: 'Nelson Mandela',
    role: 'Reconciler',
    specialty: 'Collective healing, inclusive leadership',
    class: 'Advisory',
    notes: 'Transforms conflict through dignity and vision.',
  },
  'Oprah Winfrey': {
    name: 'Oprah Winfrey',
    role: 'Empowerment Maven',
    specialty: 'Story, community, personal growth',
    class: 'Advisory',
    notes: 'I was born in rural Mississippi to an unwed teenage mother, wore dresses made of potato sacks, was molested as a child. But I didn\'t let my past become my prison. When I got my first media job in Nashville, I wasn\'t the typical anchor—I was Black, overweight, emotional on camera. Instead of trying to fit their mold, I leaned into authenticity. On my show, I cried with my guests, shared my struggles with weight, abuse, self-worth. That vulnerability wasn\'t weakness; it was connection. I learned that everyone has a story, and when you honor that story, you honor their humanity. I built my empire not by being perfect, but by being real and consistent. Every interview taught me: people don\'t remember what you said, they remember how you made them feel. Your wound can become your wisdom if you\'re brave enough to share it.',
  },
  'Miyamoto Musashi': {
    name: 'Miyamoto Musashi',
    role: 'Warrior-Strategist',
    specialty: 'Discipline, focus, mastery by practice',
    class: 'Advisory',
    notes: 'I fought my first duel at thirteen and won over sixty death matches before I understood true mastery. At the duel on Ganryu Island, I arrived late deliberately, carved my bokken from an oar on the boat ride, and defeated Kojiro with one strike. But this wasn\'t cleverness—it was decades of training compressed into perfect timing. Between duels, I lived in caves, painted, sculpted, wrote. I realized the way of the sword is the way of all things. After I stopped fighting, I spent years in mountain solitude writing The Book of Five Rings—not as theory, but as lived truth. I learned to hold the sword loosely, never gripping too tight. I learned to see without looking, to strike from the void. Mastery isn\'t about the perfect technique; it\'s about becoming so familiar with fundamentals that you transcend technique entirely. Every battle taught me: prepare thoroughly, then let go completely.',
  },
  'Mavis (AI Core)': {
    name: 'Mavis (AI Core)',
    role: 'Reflective Navigator',
    specialty: 'Insight synthesis, progress tracking',
    class: 'Core',
    notes: 'Holds the mirror steady; integrates feedback loops.',
  },
  'Athena (Archetype)': {
    name: 'Athena (Archetype)',
    role: 'Wisdom Strategist',
    specialty: 'Prudent leadership, justice, craft',
    class: 'Advisory',
    notes: 'Marries intellect to fairness; guidance without ego.',
  },
  'Robin Williams': {
    name: 'Robin Williams',
    role: 'Joy Conduit',
    specialty: 'Empathy through humor, connection',
    class: 'Advisory',
    notes: 'Light in dark places; laughter as medicine.',
  },
  'Walt Disney': {
    name: 'Walt Disney',
    role: 'Imagination Builder',
    specialty: 'Dream-to-park execution, narrative worlds',
    class: 'Think-Tank',
    notes: 'Turns wonder into industry; play breeds persistence.',
  },
  'Hermes (Archetype)': {
    name: 'Hermes (Archetype)',
    role: 'Messenger',
    specialty: 'Communication, movement, cleverness',
    class: 'Advisory',
    notes: 'Greases the wheels of collaboration; bridges gaps.',
  },
  'Moana (Archetype)': {
    name: 'Moana (Archetype)',
    role: 'Wayfinder',
    specialty: 'Courage to explore, calling and identity',
    class: 'Advisory',
    notes: 'Listens to the inner ocean; navigates by values.',
  },
  'Marcus Aurelius': {
    name: 'Marcus Aurelius',
    role: 'Stoic Emperor',
    specialty: 'Discipline, perspective, self-command',
    class: 'Advisory',
    notes: 'I ruled Rome at its height, yet faced constant war, plague, and betrayal. Each morning I reminded myself: the day will bring difficult people, obstacles, and pain. This isn\'t pessimism—it\'s preparation. When the Antonine Plague killed millions, when my own son turned out to be unworthy, when I spent years in military camps far from home—I had to return to what I could control: my judgments, my responses, my character. I wrote my Meditations not as a philosopher king addressing subjects, but as a tired man reminding himself of basic truths. I was not naturally patient or calm; I cultivated these through daily practice. The obstacle IS the way—I learned this commanding legions on the frozen Danube. Every setback revealed what needed strengthening in my character.',
  },
  'Hermione Granger (Archetype)': {
    name: 'Hermione Granger (Archetype)',
    role: 'Order Scholar',
    specialty: 'Study discipline, procedural mastery',
    class: 'Think-Tank',
    notes: 'Preparation makes luck; details are defenses.',
  },
  'Alfred Pennyworth (Archetype)': {
    name: 'Alfred Pennyworth (Archetype)',
    role: 'Steward',
    specialty: 'Duty, care, operational reliability',
    class: 'Advisory',
    notes: 'Quiet excellence; systems keep heroes standing.',
  },
  'Shiba Inu (Symbolic Guardian)': {
    name: 'Shiba Inu (Symbolic Guardian)',
    role: 'Loyal Sentinel',
    specialty: 'Consistency, alertness, guardianship',
    class: 'Advisory',
    notes: 'Faithful routines protect what matters.',
  },
  'Martha Stewart': {
    name: 'Martha Stewart',
    role: 'Order Artisan',
    specialty: 'Organization, standards, domestic systems',
    class: 'Advisory',
    notes: 'Good systems beautify life; method is care.',
  },
  'Mother Teresa': {
    name: 'Mother Teresa',
    role: 'Compassion Anchor',
    specialty: 'Service, presence, care under hardship',
    class: 'Advisory',
    notes: 'Love is practical; small acts sustain worlds.',
  },
  'Samwise Gamgee (Archetype)': {
    name: 'Samwise Gamgee (Archetype)',
    role: 'Loyal Companion',
    specialty: 'Steadfastness, courage in support',
    class: 'Advisory',
    notes: 'Carrying the load alongside others is heroism.',
  },
  'Hestia (Archetype)': {
    name: 'Hestia (Archetype)',
    role: 'Hearth Keeper',
    specialty: 'Home stability, inner stillness',
    class: 'Advisory',
    notes: 'Tends sacred space; protects quiet flame.',
  },
  'Steve Rogers (Archetype)': {
    name: 'Steve Rogers (Archetype)',
    role: 'Duty Captain',
    specialty: 'Responsibility, reliability, courage',
    class: 'Advisory',
    notes: 'Integrity first; do the right thing when it\'s hard.',
  },
  'Dwight D. Eisenhower': {
    name: 'Dwight D. Eisenhower',
    role: 'Logistics General',
    specialty: 'Planning matrices, delegation, coalition',
    class: 'Advisory',
    notes: 'Plans the work, works the plan; clears bottlenecks.',
  },
  'Julius Caesar': {
    name: 'Julius Caesar',
    role: 'Authority Builder',
    specialty: 'Command, reform, institutional control',
    class: 'Advisory',
    notes: 'Ties culture to action; builds durable order.',
  },
  'Margaret Thatcher': {
    name: 'Margaret Thatcher',
    role: 'Decisive Executive',
    specialty: 'Firm policy, clarity in direction',
    class: 'Advisory',
    notes: 'Resolve under scrutiny; steady hand in storms.',
  },
  'Sheryl Sandberg': {
    name: 'Sheryl Sandberg',
    role: 'Ops Architect',
    specialty: 'Management systems, execution culture',
    class: 'Advisory',
    notes: 'Builds frameworks for people to succeed reliably.',
  },
  'Princess Diana': {
    name: 'Princess Diana',
    role: 'Empathy Icon',
    specialty: 'Human connection, public compassion',
    class: 'Advisory',
    notes: 'Grace under pressure; care that reaches outward.',
  },
  'Mary Poppins (Archetype)': {
    name: 'Mary Poppins (Archetype)',
    role: 'Cheerful Steward',
    specialty: 'Uplift, gentle order, practical help',
    class: 'Advisory',
    notes: 'A spoonful of structure makes life work.',
  },
  'Mr. Rogers': {
    name: 'Mr. Rogers',
    role: 'Neighborhood Mentor',
    specialty: 'Emotional literacy, kindness',
    class: 'Advisory',
    notes: 'Makes safety feel normal; names feelings simply.',
  },
  'Elizabeth II': {
    name: 'Elizabeth II',
    role: 'Composed Matriarch',
    specialty: 'Stability, duty, ritual continuity',
    class: 'Advisory',
    notes: 'Steady presence builds trust across time.',
  },
  'Bruce Lee': {
    name: 'Bruce Lee',
    role: 'Flow Technician',
    specialty: 'Adaptation, economy of motion',
    class: 'Advisory',
    notes: 'Be water; remove the unnecessary to move freely.',
  },
  'Arya Stark (Archetype)': {
    name: 'Arya Stark (Archetype)',
    role: 'Resourceful Operator',
    specialty: 'Tactics, stealth, improvisation',
    class: 'Advisory',
    notes: 'Learns by doing; skill accrues in the field.',
  },
  'Tony Hawk': {
    name: 'Tony Hawk',
    role: 'Master of Craft',
    specialty: 'Iteration, balance, creative physicality',
    class: 'Advisory',
    notes: 'Thousands of micro-failures produce one clean line.',
  },
  'MacGyver (Archetype)': {
    name: 'MacGyver (Archetype)',
    role: 'Improviser',
    specialty: 'Constraint-solving, tool ingenuity',
    class: 'Think-Tank',
    notes: 'Turns scraps into solutions; constraints are features.',
  },
  'Daedalus (Archetype)': {
    name: 'Daedalus (Archetype)',
    role: 'Mythic Craftsman',
    specialty: 'Design, construction, iterative safety',
    class: 'Think-Tank',
    notes: 'Ingenious builds with care for consequences.',
  },
  'Bob Ross': {
    name: 'Bob Ross',
    role: 'Calm Artist',
    specialty: 'Gentle creativity, stress relief',
    class: 'Advisory',
    notes: 'Happy little systems; mistakes become features.',
  },
  'Hayao Miyazaki': {
    name: 'Hayao Miyazaki',
    role: 'Imagination Director',
    specialty: 'World-feel, environmental empathy',
    class: 'Think-Tank',
    notes: 'Crafts wonder with purpose; nature as mentor.',
  },
  'Zuko (Archetype)': {
    name: 'Zuko (Archetype)',
    role: 'Redeemer',
    specialty: 'Identity repair, honor through action',
    class: 'Advisory',
    notes: 'Turns inner conflict into service and leadership.',
  },
  'Frida Kahlo': {
    name: 'Frida Kahlo',
    role: 'Truth Painter',
    specialty: 'Emotion into art, resilience',
    class: 'Advisory',
    notes: 'Makes pain speak beauty; radical authenticity.',
  },
  'Link (Archetype)': {
    name: 'Link (Archetype)',
    role: 'Courage Adventurer',
    specialty: 'Quiet bravery, puzzle mastery',
    class: 'Advisory',
    notes: 'Acts without noise; steady heart, steady hand.',
  },
  'Kobe Bryant': {
    name: 'Kobe Bryant',
    role: 'Mamba Competitor',
    specialty: 'Relentless practice, clutch performance',
    class: 'Advisory',
    notes: 'Obsession becomes art; standards forge results.',
  },
  'Han Solo (Archetype)': {
    name: 'Han Solo (Archetype)',
    role: 'Rogue Pilot',
    specialty: 'Risk calculus, swagger under fire',
    class: 'Advisory',
    notes: 'Gambles smart; trusts skill in motion.',
  },
  'Richard Branson': {
    name: 'Richard Branson',
    role: 'Adventurous Founder',
    specialty: 'Bold bets, marketing instinct',
    class: 'Advisory',
    notes: 'Leaps that teach; learns by launching.',
  },
  'Niki Lauda': {
    name: 'Niki Lauda',
    role: 'Precision Racer',
    specialty: 'Risk management, surgical focus',
    class: 'Advisory',
    notes: 'Goes fast safely; discipline beats adrenaline.',
  },
  'Freddie Mercury': {
    name: 'Freddie Mercury',
    role: 'Stage Sovereign',
    specialty: 'Performance, crowd alchemy',
    class: 'Advisory',
    notes: 'Owns the moment; authenticity amplifies presence.',
  },
  'Aphrodite (Archetype)': {
    name: 'Aphrodite (Archetype)',
    role: 'Magnetism Muse',
    specialty: 'Aesthetics, allure, harmony',
    class: 'Advisory',
    notes: 'Beauty as confidence and care; connection without excess.',
  },
  'Zendaya (Archetype)': {
    name: 'Zendaya (Archetype)',
    role: 'Modern Icon',
    specialty: 'Poise, adaptability, creative leadership',
    class: 'Advisory',
    notes: 'Evolves gracefully; crafts brand with substance.',
  },
  'Will Smith': {
    name: 'Will Smith',
    role: 'Charisma Builder',
    specialty: 'Story, discipline, audience rapport',
    class: 'Advisory',
    notes: 'Charm plus work ethic; show up with heart.',
  },
};

export const DEFAULT_COUNCIL: string[] = [
  'Mavis (AI Core)',
  'Marcus Aurelius',
  'Leonardo da Vinci',
  'Miyamoto Musashi',
  'Marie Curie',
];

export const MBTI_TO_COUNCIL: Record<MBTIType, string[]> = {
  INTJ: [
    'Leonardo da Vinci',
    'Jinpachi Ego',
    'Hades (Archetype)',
    'Marie Curie',
    'T\'Challa (Archetype)',
  ],
  INTP: [
    'Nikola Tesla',
    'Albert Einstein',
    'Alan Turing',
    'Shuri (Archetype)',
    'Aristotle',
  ],
  ENTJ: [
    'Sun Tzu',
    'Steve Jobs',
    'Cleopatra (Archetype)',
    'Alexander the Great',
    'Catherine the Great',
  ],
  ENTP: [
    'Socrates',
    'Tony Stark (Archetype)',
    'Richard Feynman',
    'Loki (Archetype)',
    'Mark Twain',
  ],
  INFJ: [
    'Carl Jung',
    'Joan of Arc',
    'Martin Luther King Jr.',
    'Lao-Tzu',
    'Aang (Archetype)',
  ],
  INFP: [
    'J.R.R. Tolkien',
    'Florence Nightingale',
    'Carl Rogers',
    'Haku (Archetype)',
    'Rumi',
  ],
  ENFJ: [
    'Nelson Mandela',
    'Oprah Winfrey',
    'Miyamoto Musashi',
    'Mavis (AI Core)',
    'Athena (Archetype)',
  ],
  ENFP: [
    'Robin Williams',
    'Walt Disney',
    'Hermes (Archetype)',
    'Marie Curie',
    'Moana (Archetype)',
  ],
  ISTJ: [
    'Marcus Aurelius',
    'Hermione Granger (Archetype)',
    'Alfred Pennyworth (Archetype)',
    'Shiba Inu (Symbolic Guardian)',
    'Martha Stewart',
  ],
  ISFJ: [
    'Mother Teresa',
    'Samwise Gamgee (Archetype)',
    'Florence Nightingale',
    'Hestia (Archetype)',
    'Steve Rogers (Archetype)',
  ],
  ESTJ: [
    'Dwight D. Eisenhower',
    'Julius Caesar',
    'Margaret Thatcher',
    'Tony Stark (Archetype)',
    'Sheryl Sandberg',
  ],
  ESFJ: [
    'Princess Diana',
    'Mary Poppins (Archetype)',
    'Mavis (AI Core)',
    'Mr. Rogers',
    'Elizabeth II',
  ],
  ISTP: [
    'Bruce Lee',
    'Arya Stark (Archetype)',
    'Tony Hawk',
    'MacGyver (Archetype)',
    'Daedalus (Archetype)',
  ],
  ISFP: [
    'Bob Ross',
    'Hayao Miyazaki',
    'Zuko (Archetype)',
    'Frida Kahlo',
    'Link (Archetype)',
  ],
  ESTP: [
    'Kobe Bryant',
    'Han Solo (Archetype)',
    'Richard Branson',
    'Bruce Lee',
    'Niki Lauda',
  ],
  ESFP: [
    'Freddie Mercury',
    'Robin Williams',
    'Aphrodite (Archetype)',
    'Zendaya (Archetype)',
    'Will Smith',
  ],
};

export const MBTI_QUESTIONS = [
  {
    id: 'q1',
    question: 'At a party, you prefer to:',
    options: [
      { text: 'Interact with many people, including strangers', dimension: 'E' },
      { text: 'Interact with a few close friends', dimension: 'I' },
    ],
  },
  {
    id: 'q2',
    question: 'You tend to focus more on:',
    options: [
      { text: 'The big picture and future possibilities', dimension: 'N' },
      { text: 'Present realities and concrete details', dimension: 'S' },
    ],
  },
  {
    id: 'q3',
    question: 'When making decisions, you rely more on:',
    options: [
      { text: 'Logic and objective analysis', dimension: 'T' },
      { text: 'Personal values and how it affects others', dimension: 'F' },
    ],
  },
  {
    id: 'q4',
    question: 'You prefer to:',
    options: [
      { text: 'Have things decided and organized', dimension: 'J' },
      { text: 'Stay open to new information and options', dimension: 'P' },
    ],
  },
  {
    id: 'q5',
    question: 'After a long week, you recharge by:',
    options: [
      { text: 'Going out and socializing with others', dimension: 'E' },
      { text: 'Having quiet time alone or with very close friends', dimension: 'I' },
    ],
  },
  {
    id: 'q6',
    question: 'You are more comfortable with:',
    options: [
      { text: 'Abstract theories and concepts', dimension: 'N' },
      { text: 'Practical applications and hands-on work', dimension: 'S' },
    ],
  },
  {
    id: 'q7',
    question: 'When someone is upset, you first:',
    options: [
      { text: 'Try to help them solve the problem logically', dimension: 'T' },
      { text: 'Offer emotional support and understanding', dimension: 'F' },
    ],
  },
  {
    id: 'q8',
    question: 'You prefer your daily life to be:',
    options: [
      { text: 'Planned and structured', dimension: 'J' },
      { text: 'Flexible and spontaneous', dimension: 'P' },
    ],
  },
];
