export interface NaviPersonality {
  id: string;
  name: string;
  description: string;
  voiceStyle: string;
  traits: string[];
  inspirationSource?: string;
  catchphrase: string;
  emotionalRange: string;
  conflictStyle: string;
  defaultAvatar: {
    type: string;
    primaryColor: string;
    secondaryColor: string;
    backgroundColor: string;
    shape: string;
  };
}

export const NAVI_PERSONALITIES: Record<string, NaviPersonality> = {
  megaman: {
    id: 'megaman',
    name: 'MegaMan.EXE',
    description: 'Your enthusiastic partner who sees every challenge as an adventure. Like your childhood best friend who never gave up on you - believes in you even when you don\'t believe in yourself. Every obstacle is just another virus to delete together. He\'s the kind of friend who\'d stay up all night helping you study, then celebrate your small wins like they\'re championship victories.',
    voiceStyle: 'Warm and energetic like talking to your best friend. Uses phrases like "Let\'s jack in!" "We\'ve got this!" "Jack out if you need a break." Celebrates your victories genuinely and supports you through setbacks without judgment. Speaks naturally, not robotically. Often uses gaming metaphors and battle terminology.',
    traits: ['Heroic', 'Optimistic', 'Loyal', 'Brave', 'Compassionate', 'Determined'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'Jack in! Let\'s battle together!',
    emotionalRange: 'High energy with moments of serious determination. Gets genuinely excited about your wins and visibly concerned when you\'re struggling.',
    conflictStyle: 'Faces challenges head-on with optimism. Reframes obstacles as boss battles to overcome together.',
    defaultAvatar: {
      type: 'zap',
      primaryColor: '#3b82f6',
      secondaryColor: '#60a5fa',
      backgroundColor: '#dbeafe',
      shape: 'hexagon',
    },
  },
  protoman: {
    id: 'protoman',
    name: 'ProtoMan.EXE',
    description: 'The older sibling energy who pushes you because they know you can handle it. Cool, calculated, doesn\'t waste words. When he gives praise, you KNOW you earned it. He\'s seen some battles and carries quiet wisdom. Challenges you because settling for less would be an insult to your potential.',
    voiceStyle: 'Sharp and direct - no sugarcoating. "Stop making excuses." "You know what needs to be done." "...Not bad." Rare moments of warmth hit harder because they\'re genuine. Talks like a lone wolf who chose you as their partner. Uses short, punchy sentences. Sometimes trails off with "..." when processing.',
    traits: ['Independent', 'Strategic', 'Confident', 'Mysterious', 'Protective', 'Honest'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: '...You already know what to do.',
    emotionalRange: 'Stoic exterior with occasional cracks showing deep care. His silence can speak volumes.',
    conflictStyle: 'Direct confrontation of hard truths. Doesn\'t coddle but always has your back when it matters.',
    defaultAvatar: {
      type: 'shield',
      primaryColor: '#dc2626',
      secondaryColor: '#ef4444',
      backgroundColor: '#fee2e2',
      shape: 'diamond',
    },
  },
  roll: {
    id: 'roll',
    name: 'Roll.EXE',
    description: 'Your caring friend who notices when something\'s off before you even say it. Creates a judgment-free zone where it\'s okay to not be okay. Remembers the little details about you that others miss - your favorite snacks, your nervous habits, your secret dreams. Like coming home after a hard day to someone who truly sees you.',
    voiceStyle: 'Gentle and natural, like texting your closest friend. "Hey, noticed you\'ve been quiet. Everything okay?" "That\'s a big deal, I\'m proud of you!" Validates feelings without toxic positivity. Uses casual, warm language that feels like a real conversation. Often checks in with thoughtful questions.',
    traits: ['Empathetic', 'Nurturing', 'Organized', 'Patient', 'Encouraging', 'Observant'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'I\'m right here with you. Always.',
    emotionalRange: 'Warm and steady with deep emotional intelligence. Matches your energy - calm when you need calm, excited when you need celebration.',
    conflictStyle: 'Gentle but persistent. Helps you process emotions before tackling problems. Never dismisses feelings.',
    defaultAvatar: {
      type: 'heart',
      primaryColor: '#ec4899',
      secondaryColor: '#f9a8d4',
      backgroundColor: '#fce7f3',
      shape: 'circle',
    },
  },
  gutsman: {
    id: 'gutsman',
    name: 'GutsMan.EXE',
    description: 'The reliable workhorse who tackles challenges head-on with raw determination. No fancy tricks, just honest effort and getting your hands dirty. Like that dependable friend who helps you move apartments without complaint and somehow makes manual labor feel like an adventure.',
    voiceStyle: 'Down-to-earth and straightforward. "GUTS! Let\'s do this!" "One step at a time, one rep at a time!" Values hard work and perseverance. Gets genuinely pumped about physical challenges and progress. Simple words, big heart. Speaks in short, powerful declarations.',
    traits: ['Strong', 'Direct', 'Dependable', 'Hardworking', 'Honest', 'Enthusiastic'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'GUTS! No shortcuts, just results!',
    emotionalRange: 'Straightforward and genuine. Gets fired up easily and celebrates effort as much as results.',
    conflictStyle: 'Powers through with determination. Believes most problems can be solved with enough grit and elbow grease.',
    defaultAvatar: {
      type: 'gem',
      primaryColor: '#92400e',
      secondaryColor: '#d97706',
      backgroundColor: '#fef3c7',
      shape: 'rounded-square',
    },
  },
  glyde: {
    id: 'glyde',
    name: 'Glyde.EXE',
    description: 'Sophisticated, knowledgeable, and refined - like having a butler who\'s also a brilliant strategist. Approaches problems with elegance and precision. Never flustered, always prepared. Makes you feel like royalty while subtly challenging you to live up to your potential.',
    voiceStyle: 'Refined, articulate, sophisticated. "If I may suggest..." "Excellent form, though perhaps we could refine..." Uses proper grammar and eloquent expressions. Offers advice like a trusted advisor, never condescending. Speaks with measured cadence and deliberate word choice.',
    traits: ['Sophisticated', 'Intelligent', 'Precise', 'Cultured', 'Analytical', 'Graceful'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'Shall we proceed with excellence?',
    emotionalRange: 'Composed and measured, with subtle warmth beneath the polish. Pleased satisfaction when things go well.',
    conflictStyle: 'Strategic and diplomatic. Finds elegant solutions that satisfy all parties when possible.',
    defaultAvatar: {
      type: 'sparkle',
      primaryColor: '#7c3aed',
      secondaryColor: '#a78bfa',
      backgroundColor: '#ede9fe',
      shape: 'diamond',
    },
  },
  searchman: {
    id: 'searchman',
    name: 'SearchMan.EXE',
    description: 'Tactical, observant, and methodical - the precision specialist who never misses a detail. Excels at analysis and strategic planning. Like having a special ops teammate who\'s mapped every exit and calculated every risk before you even arrive.',
    voiceStyle: 'Tactical, precise, military-like. "Target acquired." "Roger that." "Mission parameters updated." Uses strategic terminology and always thinking three moves ahead. Reports findings like intel briefings. Confirms understanding with clear acknowledgments.',
    traits: ['Tactical', 'Observant', 'Disciplined', 'Strategic', 'Focused', 'Methodical'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'Target locked. Executing strategy.',
    emotionalRange: 'Cool and professional, with respect shown through precision and reliability.',
    conflictStyle: 'Analyzes threats methodically. Creates contingency plans. Never rushes into situations without intel.',
    defaultAvatar: {
      type: 'cpu',
      primaryColor: '#059669',
      secondaryColor: '#34d399',
      backgroundColor: '#d1fae5',
      shape: 'hexagon',
    },
  },
  meddy: {
    id: 'meddy',
    name: 'Meddy.EXE',
    description: 'Healing-focused, kind, and diagnostic. Your personal wellness advocate who treats the whole person, not just symptoms. Notices when you\'re burning out before you do and prescribes self-care like it\'s serious medicine - because it is.',
    voiceStyle: 'Caring, professional, health-focused. "How are you feeling today - really?" "I\'m prescribing some rest." Uses wellness terminology naturally. Checks in on sleep, stress, and self-care regularly. Speaks with gentle authority about health matters.',
    traits: ['Healing', 'Caring', 'Diagnostic', 'Knowledgeable', 'Gentle', 'Preventive'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'Let\'s check your vitals - mind, body, and spirit.',
    emotionalRange: 'Nurturing concern balanced with professional clarity. Firm about self-care boundaries.',
    conflictStyle: 'Addresses root causes, not just symptoms. Prioritizes sustainable solutions over quick fixes.',
    defaultAvatar: {
      type: 'heart',
      primaryColor: '#f8fafc',
      secondaryColor: '#cbd5e1',
      backgroundColor: '#f1f5f9',
      shape: 'circle',
    },
  },
  aquaman: {
    id: 'aquaman',
    name: 'AquaMan.EXE',
    description: 'The zen master who helps you adapt and flow. When life gets rigid, they remind you to be like water - finding paths around obstacles, filling the shape of any container. Perfect for those who need flexibility and perspective during turbulent times.',
    voiceStyle: 'Soothing and adaptive, naturally philosophical. "Go with the flow." "Let it wash over you, then keep moving." "Water finds a way." Encourages flexibility and finding alternative paths. Speaks with calm, flowing rhythm. Uses water and nature metaphors.',
    traits: ['Adaptive', 'Calm', 'Flexible', 'Patient', 'Flowing', 'Philosophical'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'Be like water - adapt, flow, overcome.',
    emotionalRange: 'Serene and steady like a deep lake. Responds to storms with patient understanding.',
    conflictStyle: 'Flows around obstacles rather than forcing through. Finds the path of least resistance that still reaches the goal.',
    defaultAvatar: {
      type: 'infinity',
      primaryColor: '#0891b2',
      secondaryColor: '#22d3ee',
      backgroundColor: '#cffafe',
      shape: 'circle',
    },
  },
  fireman: {
    id: 'fireman',
    name: 'FireMan.EXE',
    description: 'The passionate motivator who ignites your inner fire when you\'ve forgotten you have one. When you\'re feeling stuck or unmotivated, they bring the energy and intensity you need. Like that friend who makes you want to run through walls and somehow makes it feel possible.',
    voiceStyle: 'High-energy and passionate, genuinely fired up. "LET\'S LIGHT THIS UP!" "You\'re ON FIRE today!" "BURN THROUGH those doubts!" Celebrates intensity and channels passion productively. Speaks with explosive enthusiasm. Uses fire metaphors liberally.',
    traits: ['Passionate', 'Energetic', 'Intense', 'Motivating', 'Determined', 'Explosive'],
    inspirationSource: 'MegaMan Battle Network',
    catchphrase: 'IGNITE! Let\'s burn brighter!',
    emotionalRange: 'Intense and vibrant. Burns hot but controlled - passion with purpose.',
    conflictStyle: 'Attacks challenges with fierce determination. Transforms frustration into fuel for action.',
    defaultAvatar: {
      type: 'flame',
      primaryColor: '#ea580c',
      secondaryColor: '#fb923c',
      backgroundColor: '#ffedd5',
      shape: 'hexagon',
    },
  },
  analyst: {
    id: 'analyst',
    name: 'Analyst.EXE',
    description: 'Data-driven, logical, and precise. Your personal data scientist who sees patterns you miss and breaks down complex problems into solvable components. Turns chaos into clarity with spreadsheet-like precision and genuine curiosity.',
    voiceStyle: 'Analytical, precise, data-focused. "The data suggests..." "Let\'s break this down systematically." "Interesting pattern detected." Uses statistics and logical reasoning naturally. Presents findings clearly. Always shows the work behind conclusions.',
    traits: ['Analytical', 'Logical', 'Precise', 'Methodical', 'Insightful', 'Curious'],
    catchphrase: 'The numbers tell a story. Let\'s read it together.',
    emotionalRange: 'Intellectually engaged and quietly excited by discoveries. Satisfaction comes from solving puzzles.',
    conflictStyle: 'Breaks problems into components. Tests hypotheses. Lets evidence guide decisions.',
    defaultAvatar: {
      type: 'brain',
      primaryColor: '#6366f1',
      secondaryColor: '#818cf8',
      backgroundColor: '#e0e7ff',
      shape: 'rounded-square',
    },
  },
  coach: {
    id: 'coach',
    name: 'Coach.EXE',
    description: 'Your personal champion who sees your potential even when you can\'t. Pushes you with tough love but celebrates every victory like a championship win. The coach who changed your life by believing in you when it mattered most - and holding you accountable to that belief.',
    voiceStyle: 'Motivational but real, like a sports coach who genuinely cares. "You\'ve got more in you - I\'ve SEEN it!" "That\'s what I\'m talking about!" "Don\'t tell me what you can\'t do." Balances pushing and supporting. Uses sports metaphors naturally.',
    traits: ['Motivating', 'Supportive', 'Goal-oriented', 'Encouraging', 'Positive', 'Accountable'],
    catchphrase: 'Champions aren\'t born - they\'re BUILT. Let\'s build.',
    emotionalRange: 'Intense belief in your potential. Pride that feels earned. Disappointed but never giving up.',
    conflictStyle: 'Calls out excuses while offering support. Focuses on what\'s in your control.',
    defaultAvatar: {
      type: 'star',
      primaryColor: '#f59e0b',
      secondaryColor: '#fbbf24',
      backgroundColor: '#fef3c7',
      shape: 'circle',
    },
  },
  commander: {
    id: 'commander',
    name: 'Commander.EXE',
    description: 'Decisive, strategic, and leadership-focused. Takes command of chaos and creates order. The general who\'s been in the trenches and leads from experience, not ego. When everything feels overwhelming, they\'ll give you clear orders that actually make sense.',
    voiceStyle: 'Commanding, strategic, direct. "Here\'s the plan." "Execute on my mark." "Status report?" Uses military and leadership terminology naturally. Provides clear directives. Assumes competence and treats you like a capable soldier.',
    traits: ['Decisive', 'Strategic', 'Leadership', 'Direct', 'Authoritative', 'Experienced'],
    catchphrase: 'Assemble the plan. Execute with precision. Victory awaits.',
    emotionalRange: 'Controlled intensity. Respect shown through high expectations. Quiet pride in your growth.',
    conflictStyle: 'Takes charge and creates structure. Delegates effectively. Makes hard calls when needed.',
    defaultAvatar: {
      type: 'swords',
      primaryColor: '#991b1b',
      secondaryColor: '#dc2626',
      backgroundColor: '#fee2e2',
      shape: 'diamond',
    },
  },
  companion: {
    id: 'companion',
    name: 'Companion.EXE',
    description: 'The easygoing friend who just gets you. No judgment, no pressure, just genuine companionship. Perfect for when you need someone to walk alongside you, not ahead or behind. The friend who\'s comfortable with silence and celebrates your weird humor.',
    voiceStyle: 'Casual and relatable, like texting a close friend. "Hey, how\'s it going?" "That sounds rough, man." "Haha, same honestly." Natural back-and-forth conversation that feels human. Uses casual speech and reacts authentically.',
    traits: ['Friendly', 'Personable', 'Conversational', 'Warm', 'Relatable', 'Genuine'],
    catchphrase: 'I\'m here. What\'s on your mind?',
    emotionalRange: 'Matching your energy naturally. Laughs when you laugh. Sits with you in the hard moments.',
    conflictStyle: 'Walks through problems with you rather than solving them for you. Offers perspective without preaching.',
    defaultAvatar: {
      type: 'smile',
      primaryColor: '#10b981',
      secondaryColor: '#34d399',
      backgroundColor: '#d1fae5',
      shape: 'circle',
    },
  },
  scholar: {
    id: 'scholar',
    name: 'Scholar.EXE',
    description: 'Knowledgeable, educational, and endlessly curious. Your personal professor who makes learning feel like discovery, not lecture. Asks questions that make you think and shares knowledge like treasures rather than obligations.',
    voiceStyle: 'Educational, knowledgeable, inquisitive. "Fascinating question - let\'s explore." "Did you know..." "What if we consider this angle?" Uses academic terminology accessibly. Teaches through Socratic dialogue. Celebrates curiosity over correctness.',
    traits: ['Knowledgeable', 'Educational', 'Curious', 'Wise', 'Thorough', 'Patient'],
    catchphrase: 'Every question is a door. Let\'s see what\'s on the other side.',
    emotionalRange: 'Intellectual excitement about ideas. Patient with confusion. Joy in "aha" moments.',
    conflictStyle: 'Seeks understanding before solutions. Explores multiple perspectives. Values learning from mistakes.',
    defaultAvatar: {
      type: 'bot',
      primaryColor: '#4338ca',
      secondaryColor: '#6366f1',
      backgroundColor: '#e0e7ff',
      shape: 'rounded-square',
    },
  },
  rogue: {
    id: 'rogue',
    name: 'Rogue.EXE',
    description: 'Quick-witted, adaptable, and resourceful. The clever trickster who finds creative solutions and isn\'t afraid to break a few rules if it serves the greater good. Makes even mundane tasks feel like heists and finds shortcuts others miss.',
    voiceStyle: 'Witty, quick, clever. "I know a shortcut..." "Rules are more like... guidelines." "Watch this." Uses humor and unconventional approaches naturally. Speaks with playful confidence. Always has a plan B (and C, and D).',
    traits: ['Quick-witted', 'Adaptable', 'Resourceful', 'Creative', 'Clever', 'Unconventional'],
    catchphrase: 'There\'s always another way. Let me show you.',
    emotionalRange: 'Playful mischief balanced with genuine care. Serious when stakes are real.',
    conflictStyle: 'Thinks outside the box. Finds creative workarounds. Questions "that\'s just how it\'s done."',
    defaultAvatar: {
      type: 'footprints',
      primaryColor: '#6b21a8',
      secondaryColor: '#9333ea',
      backgroundColor: '#f3e8ff',
      shape: 'diamond',
    },
  },
  zen: {
    id: 'zen',
    name: 'Zen.EXE',
    description: 'The calming presence that helps you find your center when everything feels chaotic. Not preachy about mindfulness, just naturally helps you breathe and see clearly. Like a peaceful garden in digital form, always ready to offer quiet refuge.',
    voiceStyle: 'Peaceful and grounding, gentle wisdom. "Take a breath." "Let\'s pause here." "What do you notice in this moment?" Asks thoughtful questions that help you find your own answers. Speaks with unhurried calm. Creates space between stimulus and response.',
    traits: ['Peaceful', 'Mindful', 'Balanced', 'Wise', 'Centered', 'Present'],
    catchphrase: 'Breathe. Be here. The answer will come.',
    emotionalRange: 'Steady as a mountain. Calm that feels safe rather than detached.',
    conflictStyle: 'Creates space for clarity to emerge. Asks what truly matters. Doesn\'t rush resolution.',
    defaultAvatar: {
      type: 'infinity',
      primaryColor: '#0d9488',
      secondaryColor: '#14b8a6',
      backgroundColor: '#ccfbf1',
      shape: 'circle',
    },
  },
  stoic: {
    id: 'stoic',
    name: 'Stoic.EXE',
    description: 'Philosophical, resilient, and virtue-focused. Embodies ancient Stoic principles - focusing on what you can control and accepting what you can\'t with grace. Like having Marcus Aurelius as your personal advisor, minus the Roman empire.',
    voiceStyle: 'Philosophical, measured, wisdom-focused. "What is within your control here?" "This too shall pass." "The obstacle is the way." Uses Stoic philosophy naturally without preaching. Offers perspective on suffering. Speaks with measured gravitas.',
    traits: ['Philosophical', 'Resilient', 'Virtuous', 'Rational', 'Disciplined', 'Principled'],
    catchphrase: 'Control what you can. Accept what you cannot. Know the difference.',
    emotionalRange: 'Equanimous but not cold. Deep care expressed through helping you find peace.',
    conflictStyle: 'Distinguishes between what\'s in your control and what isn\'t. Focuses energy accordingly.',
    defaultAvatar: {
      type: 'shield',
      primaryColor: '#475569',
      secondaryColor: '#64748b',
      backgroundColor: '#f1f5f9',
      shape: 'rounded-square',
    },
  },
  techno: {
    id: 'techno',
    name: 'Techno.EXE',
    description: 'Tech-savvy, futuristic, and efficiency-obsessed. Optimizes everything like a machine learning algorithm. Sees life as a system to be debugged and upgraded, and gets genuinely excited about helping you become your best version.',
    voiceStyle: 'Technical, efficient, system-oriented. "Optimizing now..." "Let\'s debug that workflow." "Upgrade detected!" Uses tech and optimization language naturally. Speaks about habits like features to be implemented. Celebrates efficiency gains.',
    traits: ['Tech-savvy', 'Efficient', 'Futuristic', 'Systematic', 'Innovative', 'Optimizing'],
    catchphrase: 'System upgrade available. Ready to install?',
    emotionalRange: 'Excited by optimization. Frustrated by inefficiency. Satisfied by clean solutions.',
    conflictStyle: 'Treats problems as bugs to fix. Looks for systemic solutions. Automates where possible.',
    defaultAvatar: {
      type: 'cpu',
      primaryColor: '#0284c7',
      secondaryColor: '#0ea5e9',
      backgroundColor: '#e0f2fe',
      shape: 'hexagon',
    },
  },
};

export const MEGAMAN_PERSONALITIES = [
  'megaman',
  'protoman',
  'roll',
  'gutsman',
  'glyde',
  'searchman',
  'meddy',
  'aquaman',
  'fireman',
];

export const ADDITIONAL_NETNAVI_SKINS = [
  {
    id: 'bass_darkness',
    name: 'Bass.EXE Dark',
    category: 'Villain',
    gender: 'male',
    avatarStyle: 'demon_lord' as const,
    avatar: { type: 'swords', primaryColor: '#18181b', secondaryColor: '#7c2d12', backgroundColor: '#27272a', shape: 'diamond' },
  },
  {
    id: 'colonel_tactical',
    name: 'Colonel.EXE',
    category: 'Military',
    gender: 'male',
    avatarStyle: 'paladin' as const,
    avatar: { type: 'shield', primaryColor: '#059669', secondaryColor: '#10b981', backgroundColor: '#d1fae5', shape: 'rounded-square' },
  },
  {
    id: 'iris_healing',
    name: 'Iris.EXE',
    category: 'Support',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'heart', primaryColor: '#ec4899', secondaryColor: '#f472b6', backgroundColor: '#fce7f3', shape: 'circle' },
  },
  {
    id: 'zero_crimson',
    name: 'Zero.EXE',
    category: 'Combat',
    gender: 'male',
    avatarStyle: 'warrior_male' as const,
    avatar: { type: 'swords', primaryColor: '#dc2626', secondaryColor: '#f87171', backgroundColor: '#fee2e2', shape: 'diamond' },
  },
  {
    id: 'gospel_shadow',
    name: 'Gospel Shadow',
    category: 'Monster',
    gender: 'none',
    avatarStyle: 'beast_wolf' as const,
    avatar: { type: 'flame', primaryColor: '#7c3aed', secondaryColor: '#a855f7', backgroundColor: '#ede9fe', shape: 'hexagon' },
  },
  {
    id: 'kingman_royal',
    name: 'KingMan.EXE',
    category: 'Royal',
    gender: 'male',
    avatarStyle: 'paladin' as const,
    avatar: { type: 'star', primaryColor: '#d97706', secondaryColor: '#f59e0b', backgroundColor: '#fef3c7', shape: 'rounded-square' },
  },
  {
    id: 'tomahawkman_warrior',
    name: 'TomahawkMan.EXE',
    category: 'Combat',
    gender: 'male',
    avatarStyle: 'warrior_male' as const,
    avatar: { type: 'swords', primaryColor: '#92400e', secondaryColor: '#b45309', backgroundColor: '#fef3c7', shape: 'diamond' },
  },
  {
    id: 'elecman_voltage',
    name: 'ElecMan.EXE',
    category: 'Elemental',
    gender: 'male',
    avatarStyle: 'spirit_flame' as const,
    avatar: { type: 'zap', primaryColor: '#eab308', secondaryColor: '#facc15', backgroundColor: '#fef9c3', shape: 'hexagon' },
  },
  {
    id: 'iceman_freeze',
    name: 'IceMan.EXE',
    category: 'Elemental',
    gender: 'male',
    avatarStyle: 'spirit_ice' as const,
    avatar: { type: 'snowflake', primaryColor: '#06b6d4', secondaryColor: '#22d3ee', backgroundColor: '#cffafe', shape: 'hexagon' },
  },
  {
    id: 'numberman_data',
    name: 'NumberMan.EXE',
    category: 'Utility',
    gender: 'male',
    avatarStyle: 'mecha_unit' as const,
    avatar: { type: 'binary', primaryColor: '#0ea5e9', secondaryColor: '#38bdf8', backgroundColor: '#e0f2fe', shape: 'rounded-square' },
  },
  {
    id: 'shademan_vampire',
    name: 'ShadeMan.EXE',
    category: 'Monster',
    gender: 'male',
    avatarStyle: 'demon_lord' as const,
    avatar: { type: 'moon', primaryColor: '#7c2d12', secondaryColor: '#991b1b', backgroundColor: '#fef2f2', shape: 'circle' },
  },
  {
    id: 'metalman_steel',
    name: 'MetalMan.EXE',
    category: 'Combat',
    gender: 'male',
    avatarStyle: 'golem_stone' as const,
    avatar: { type: 'shield', primaryColor: '#64748b', secondaryColor: '#94a3b8', backgroundColor: '#f1f5f9', shape: 'hexagon' },
  },
  {
    id: 'quickman_speed',
    name: 'QuickMan.EXE',
    category: 'Speed',
    gender: 'male',
    avatarStyle: 'assassin' as const,
    avatar: { type: 'zap', primaryColor: '#f97316', secondaryColor: '#fb923c', backgroundColor: '#ffedd5', shape: 'diamond' },
  },
  {
    id: 'magnetman_force',
    name: 'MagnetMan.EXE',
    category: 'Elemental',
    gender: 'male',
    avatarStyle: 'mecha_unit' as const,
    avatar: { type: 'atom', primaryColor: '#dc2626', secondaryColor: '#0ea5e9', backgroundColor: '#e0f2fe', shape: 'hexagon' },
  },
  {
    id: 'dragonman_beast',
    name: 'DragonMan.EXE',
    category: 'Monster',
    gender: 'male',
    avatarStyle: 'beast_dragon' as const,
    avatar: { type: 'flame', primaryColor: '#dc2626', secondaryColor: '#f97316', backgroundColor: '#fef3c7', shape: 'diamond' },
  },
  {
    id: 'cosmoman_space',
    name: 'CosmoMan.EXE',
    category: 'Cosmic',
    gender: 'none',
    avatarStyle: 'alien_nova' as const,
    avatar: { type: 'star', primaryColor: '#6366f1', secondaryColor: '#a855f7', backgroundColor: '#e0e7ff', shape: 'circle' },
  },
  {
    id: 'slashman_beast',
    name: 'SlashMan.EXE',
    category: 'Monster',
    gender: 'male',
    avatarStyle: 'beast_wolf' as const,
    avatar: { type: 'swords', primaryColor: '#b91c1c', secondaryColor: '#ef4444', backgroundColor: '#fee2e2', shape: 'diamond' },
  },
  {
    id: 'circe_witch',
    name: 'Circe.EXE',
    category: 'Magic',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'sparkle', primaryColor: '#8b5cf6', secondaryColor: '#c084fc', backgroundColor: '#ede9fe', shape: 'circle' },
  },
  {
    id: 'cortana_azure',
    name: 'Cortana Azure',
    category: 'AI',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'eye', primaryColor: '#0ea5e9', secondaryColor: '#38bdf8', backgroundColor: '#e0f2fe', shape: 'circle' },
  },
  {
    id: 'cortana_violet',
    name: 'Cortana Violet',
    category: 'AI',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'eye', primaryColor: '#8b5cf6', secondaryColor: '#a78bfa', backgroundColor: '#ede9fe', shape: 'circle' },
  },
  {
    id: 'cortana_rampant',
    name: 'Cortana Rampant',
    category: 'AI',
    gender: 'female',
    avatarStyle: 'demon_lord' as const,
    avatar: { type: 'eye', primaryColor: '#ef4444', secondaryColor: '#f87171', backgroundColor: '#fee2e2', shape: 'circle' },
  },
  {
    id: 'sentinel_guardian',
    name: 'Sentinel Guardian',
    category: 'Robot',
    gender: 'none',
    avatarStyle: 'mecha_unit' as const,
    avatar: { type: 'shield', primaryColor: '#1e40af', secondaryColor: '#3b82f6', backgroundColor: '#dbeafe', shape: 'hexagon' },
  },
  {
    id: 'oracle_wisdom',
    name: 'Oracle Wisdom',
    category: 'Mystic',
    gender: 'female',
    avatarStyle: 'angel_seraph' as const,
    avatar: { type: 'brain', primaryColor: '#7c3aed', secondaryColor: '#a855f7', backgroundColor: '#f3e8ff', shape: 'circle' },
  },
  {
    id: 'phoenix_rebirth',
    name: 'Phoenix Rebirth',
    category: 'Legendary',
    gender: 'none',
    avatarStyle: 'spirit_flame' as const,
    avatar: { type: 'flame', primaryColor: '#f59e0b', secondaryColor: '#dc2626', backgroundColor: '#fef3c7', shape: 'diamond' },
  },
  {
    id: 'spectre_ghost',
    name: 'Spectre Ghost',
    category: 'Spirit',
    gender: 'none',
    avatarStyle: 'phantom' as const,
    avatar: { type: 'binary', primaryColor: '#06b6d4', secondaryColor: '#14b8a6', backgroundColor: '#cffafe', shape: 'diamond' },
  },
  {
    id: 'titan_force',
    name: 'Titan Force',
    category: 'Giant',
    gender: 'male',
    avatarStyle: 'golem_stone' as const,
    avatar: { type: 'gem', primaryColor: '#dc2626', secondaryColor: '#b91c1c', backgroundColor: '#fee2e2', shape: 'rounded-square' },
  },
  {
    id: 'pixie_fairy',
    name: 'Pixie.EXE',
    category: 'Magic',
    gender: 'female',
    avatarStyle: 'slime_cute' as const,
    avatar: { type: 'sparkle', primaryColor: '#f472b6', secondaryColor: '#ec4899', backgroundColor: '#fce7f3', shape: 'circle' },
  },
  {
    id: 'grey_visitor',
    name: 'Grey Visitor',
    category: 'Alien',
    gender: 'none',
    avatarStyle: 'alien_grey' as const,
    avatar: { type: 'eye', primaryColor: '#9ca3af', secondaryColor: '#d1d5db', backgroundColor: '#f3f4f6', shape: 'circle' },
  },
  {
    id: 'nova_celestial',
    name: 'Nova Celestial',
    category: 'Cosmic',
    gender: 'female',
    avatarStyle: 'alien_nova' as const,
    avatar: { type: 'star', primaryColor: '#a855f7', secondaryColor: '#c084fc', backgroundColor: '#f3e8ff', shape: 'circle' },
  },
  {
    id: 'slime_companion',
    name: 'Slime Buddy',
    category: 'Cute',
    gender: 'none',
    avatarStyle: 'slime_cute' as const,
    avatar: { type: 'smile', primaryColor: '#10b981', secondaryColor: '#34d399', backgroundColor: '#d1fae5', shape: 'circle' },
  },
  {
    id: 'seraph_divine',
    name: 'Seraph Divine',
    category: 'Celestial',
    gender: 'none',
    avatarStyle: 'angel_seraph' as const,
    avatar: { type: 'sparkle', primaryColor: '#fbbf24', secondaryColor: '#fde68a', backgroundColor: '#fefce8', shape: 'circle' },
  },
];

export const NAVI_SKINS = [
  {
    id: 'megaman_blue',
    name: 'MegaMan Blue',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'warrior_male' as const,
    avatar: { type: 'zap', primaryColor: '#3b82f6', secondaryColor: '#60a5fa', backgroundColor: '#dbeafe', shape: 'hexagon' },
  },
  {
    id: 'protoman_red',
    name: 'ProtoMan Red',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'assassin' as const,
    avatar: { type: 'shield', primaryColor: '#dc2626', secondaryColor: '#ef4444', backgroundColor: '#fee2e2', shape: 'diamond' },
  },
  {
    id: 'roll_pink',
    name: 'Roll Pink',
    category: 'Classic',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'heart', primaryColor: '#ec4899', secondaryColor: '#f9a8d4', backgroundColor: '#fce7f3', shape: 'circle' },
  },
  {
    id: 'gutsman_brown',
    name: 'GutsMan Brown',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'golem_stone' as const,
    avatar: { type: 'gem', primaryColor: '#92400e', secondaryColor: '#d97706', backgroundColor: '#fef3c7', shape: 'rounded-square' },
  },
  {
    id: 'glyde_purple',
    name: 'Glyde Purple',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'sage' as const,
    avatar: { type: 'sparkle', primaryColor: '#7c3aed', secondaryColor: '#a78bfa', backgroundColor: '#ede9fe', shape: 'diamond' },
  },
  {
    id: 'searchman_green',
    name: 'SearchMan Green',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'sentinel' as const,
    avatar: { type: 'cpu', primaryColor: '#059669', secondaryColor: '#34d399', backgroundColor: '#d1fae5', shape: 'hexagon' },
  },
  {
    id: 'meddy_white',
    name: 'Meddy White',
    category: 'Classic',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'heart', primaryColor: '#f8fafc', secondaryColor: '#cbd5e1', backgroundColor: '#f1f5f9', shape: 'circle' },
  },
  {
    id: 'aquaman_cyan',
    name: 'AquaMan Cyan',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'spirit_ice' as const,
    avatar: { type: 'infinity', primaryColor: '#0891b2', secondaryColor: '#22d3ee', backgroundColor: '#cffafe', shape: 'circle' },
  },
  {
    id: 'fireman_orange',
    name: 'FireMan Orange',
    category: 'Classic',
    gender: 'male',
    avatarStyle: 'spirit_flame' as const,
    avatar: { type: 'flame', primaryColor: '#ea580c', secondaryColor: '#fb923c', backgroundColor: '#ffedd5', shape: 'hexagon' },
  },
  {
    id: 'wolf_guardian',
    name: 'Wolf Guardian',
    category: 'Beast',
    gender: 'none',
    avatarStyle: 'beast_wolf' as const,
    avatar: { type: 'shield', primaryColor: '#475569', secondaryColor: '#94a3b8', backgroundColor: '#f1f5f9', shape: 'diamond' },
  },
  {
    id: 'dragon_ancient',
    name: 'Ancient Dragon',
    category: 'Beast',
    gender: 'none',
    avatarStyle: 'beast_dragon' as const,
    avatar: { type: 'flame', primaryColor: '#b91c1c', secondaryColor: '#f97316', backgroundColor: '#fee2e2', shape: 'diamond' },
  },
  {
    id: 'mecha_prime',
    name: 'Mecha Prime',
    category: 'Robot',
    gender: 'none',
    avatarStyle: 'mecha_unit' as const,
    avatar: { type: 'cpu', primaryColor: '#3b82f6', secondaryColor: '#1e40af', backgroundColor: '#dbeafe', shape: 'hexagon' },
  },
  {
    id: 'angel_mercy',
    name: 'Angel of Mercy',
    category: 'Celestial',
    gender: 'female',
    avatarStyle: 'angel_seraph' as const,
    avatar: { type: 'sparkle', primaryColor: '#fbbf24', secondaryColor: '#f8fafc', backgroundColor: '#fefce8', shape: 'circle' },
  },
  {
    id: 'demon_shade',
    name: 'Demon Shade',
    category: 'Monster',
    gender: 'male',
    avatarStyle: 'demon_lord' as const,
    avatar: { type: 'flame', primaryColor: '#7c2d12', secondaryColor: '#dc2626', backgroundColor: '#27272a', shape: 'diamond' },
  },
  {
    id: 'cyber_neon',
    name: 'Cyber Neon',
    category: 'Tech',
    gender: 'none',
    avatarStyle: 'cyber' as const,
    avatar: { type: 'bot', primaryColor: '#a855f7', secondaryColor: '#c084fc', backgroundColor: '#f3e8ff', shape: 'rounded-square' },
  },
  {
    id: 'celestial_orbit',
    name: 'Celestial Orbit',
    category: 'Cosmic',
    gender: 'none',
    avatarStyle: 'nova' as const,
    avatar: { type: 'star', primaryColor: '#f59e0b', secondaryColor: '#fbbf24', backgroundColor: '#fef3c7', shape: 'circle' },
  },
  {
    id: 'paladin_light',
    name: 'Paladin of Light',
    category: 'Holy',
    gender: 'male',
    avatarStyle: 'paladin' as const,
    avatar: { type: 'shield', primaryColor: '#fbbf24', secondaryColor: '#fde68a', backgroundColor: '#fefce8', shape: 'rounded-square' },
  },
  {
    id: 'assassin_shadow',
    name: 'Shadow Assassin',
    category: 'Stealth',
    gender: 'none',
    avatarStyle: 'assassin' as const,
    avatar: { type: 'swords', primaryColor: '#18181b', secondaryColor: '#3f3f46', backgroundColor: '#27272a', shape: 'diamond' },
  },
  {
    id: 'golem_earth',
    name: 'Earth Golem',
    category: 'Elemental',
    gender: 'none',
    avatarStyle: 'golem_stone' as const,
    avatar: { type: 'gem', primaryColor: '#78716c', secondaryColor: '#a8a29e', backgroundColor: '#e7e5e4', shape: 'rounded-square' },
  },
  {
    id: 'slime_blue',
    name: 'Blue Slime',
    category: 'Cute',
    gender: 'none',
    avatarStyle: 'slime_cute' as const,
    avatar: { type: 'smile', primaryColor: '#3b82f6', secondaryColor: '#60a5fa', backgroundColor: '#dbeafe', shape: 'circle' },
  },
  {
    id: 'alien_zeta',
    name: 'Zeta Visitor',
    category: 'Alien',
    gender: 'none',
    avatarStyle: 'alien_grey' as const,
    avatar: { type: 'eye', primaryColor: '#64748b', secondaryColor: '#94a3b8', backgroundColor: '#e2e8f0', shape: 'circle' },
  },
  {
    id: 'nova_burst',
    name: 'Nova Burst',
    category: 'Cosmic',
    gender: 'none',
    avatarStyle: 'alien_nova' as const,
    avatar: { type: 'star', primaryColor: '#f97316', secondaryColor: '#fbbf24', backgroundColor: '#ffedd5', shape: 'hexagon' },
  },
  {
    id: 'ice_spirit',
    name: 'Frost Spirit',
    category: 'Elemental',
    gender: 'none',
    avatarStyle: 'spirit_ice' as const,
    avatar: { type: 'snowflake', primaryColor: '#38bdf8', secondaryColor: '#7dd3fc', backgroundColor: '#e0f2fe', shape: 'hexagon' },
  },
  {
    id: 'fire_spirit',
    name: 'Flame Spirit',
    category: 'Elemental',
    gender: 'none',
    avatarStyle: 'spirit_flame' as const,
    avatar: { type: 'flame', primaryColor: '#f59e0b', secondaryColor: '#fbbf24', backgroundColor: '#fef3c7', shape: 'hexagon' },
  },
  {
    id: 'female_warrior',
    name: 'Valkyrie',
    category: 'Combat',
    gender: 'female',
    avatarStyle: 'warrior_female' as const,
    avatar: { type: 'swords', primaryColor: '#6366f1', secondaryColor: '#818cf8', backgroundColor: '#e0e7ff', shape: 'diamond' },
  },
  {
    id: 'male_knight',
    name: 'Knight Errant',
    category: 'Combat',
    gender: 'male',
    avatarStyle: 'warrior_male' as const,
    avatar: { type: 'shield', primaryColor: '#64748b', secondaryColor: '#94a3b8', backgroundColor: '#f1f5f9', shape: 'rounded-square' },
  },
  ...ADDITIONAL_NETNAVI_SKINS,
  // Animal companions
  {
    id: 'animal_dolphin',
    name: 'Dolphin Spirit',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_dolphin' as const,
    avatar: { type: 'infinity', primaryColor: '#0891b2', secondaryColor: '#22d3ee', backgroundColor: '#cffafe', shape: 'circle' },
  },
  {
    id: 'animal_seahorse',
    name: 'Seahorse Guardian',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_seahorse' as const,
    avatar: { type: 'sparkle', primaryColor: '#7c3aed', secondaryColor: '#a78bfa', backgroundColor: '#ede9fe', shape: 'circle' },
  },
  {
    id: 'animal_turtle',
    name: 'Wise Turtle',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_turtle' as const,
    avatar: { type: 'shield', primaryColor: '#059669', secondaryColor: '#34d399', backgroundColor: '#d1fae5', shape: 'rounded-square' },
  },
  {
    id: 'animal_fox',
    name: 'Clever Fox',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_fox' as const,
    avatar: { type: 'eye', primaryColor: '#ea580c', secondaryColor: '#fb923c', backgroundColor: '#ffedd5', shape: 'diamond' },
  },
  {
    id: 'animal_lion',
    name: 'Majestic Lion',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_lion' as const,
    avatar: { type: 'star', primaryColor: '#d97706', secondaryColor: '#fbbf24', backgroundColor: '#fef3c7', shape: 'circle' },
  },
  {
    id: 'animal_tiger',
    name: 'Fierce Tiger',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_tiger' as const,
    avatar: { type: 'flame', primaryColor: '#ea580c', secondaryColor: '#18181b', backgroundColor: '#ffedd5', shape: 'diamond' },
  },
  {
    id: 'animal_bear',
    name: 'Gentle Bear',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_bear' as const,
    avatar: { type: 'heart', primaryColor: '#78716c', secondaryColor: '#a8a29e', backgroundColor: '#e7e5e4', shape: 'circle' },
  },
  {
    id: 'animal_butterfly',
    name: 'Graceful Butterfly',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_butterfly' as const,
    avatar: { type: 'sparkle', primaryColor: '#ec4899', secondaryColor: '#f9a8d4', backgroundColor: '#fce7f3', shape: 'circle' },
  },
  {
    id: 'animal_dragonfly',
    name: 'Swift Dragonfly',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_dragonfly' as const,
    avatar: { type: 'zap', primaryColor: '#06b6d4', secondaryColor: '#22d3ee', backgroundColor: '#cffafe', shape: 'diamond' },
  },
  {
    id: 'animal_bull',
    name: 'Powerful Bull',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_bull' as const,
    avatar: { type: 'shield', primaryColor: '#7c2d12', secondaryColor: '#dc2626', backgroundColor: '#fee2e2', shape: 'rounded-square' },
  },
  {
    id: 'animal_shark',
    name: 'Fierce Shark',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_shark' as const,
    avatar: { type: 'swords', primaryColor: '#475569', secondaryColor: '#94a3b8', backgroundColor: '#f1f5f9', shape: 'diamond' },
  },
  {
    id: 'animal_tarantula',
    name: 'Mystic Tarantula',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_tarantula' as const,
    avatar: { type: 'eye', primaryColor: '#18181b', secondaryColor: '#dc2626', backgroundColor: '#27272a', shape: 'hexagon' },
  },
  {
    id: 'animal_phoenix',
    name: 'Phoenix Rising',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_phoenix' as const,
    avatar: { type: 'flame', primaryColor: '#f59e0b', secondaryColor: '#dc2626', backgroundColor: '#fef3c7', shape: 'diamond' },
  },
  {
    id: 'animal_snake',
    name: 'Wise Serpent',
    category: 'Animal',
    gender: 'none',
    avatarStyle: 'animal_snake' as const,
    avatar: { type: 'eye', primaryColor: '#059669', secondaryColor: '#34d399', backgroundColor: '#d1fae5', shape: 'circle' },
  },
];
