import type { AppState } from '@/types';

export const APP_CONFIG = {
  enableCouncils: false,
  enableBoard: false,
  enableNaviEXE: true,
  enableRPG: true,
  enableProposalsGate: true,
  enableCrossSessionMemory: true,
  enableRealtimeSync: true,
  enableExternalIntegrations: false,
};

export const INITIAL_STATE: AppState = {
  user: {
    id: 'u-0001',
    name: 'You',
    avatar: '',
    focusRhythm: 'morning-calm / work-focus / evening-unwind',
    timezone: 'America/New_York',
    hasCompletedAssessment: false,
  },
  skills: [
    {
      id: 's-focus',
      name: 'Focus',
      level: 12,
      xp: 600,
      tags: ['productivity'],
      notes: 'Short bursts work best',
    },
    {
      id: 's-strength',
      name: 'Strength Training',
      level: 8,
      xp: 320,
      tags: ['health'],
      notes: '2x/week minimum',
    },
  ],
  stats: [
    { id: 'st-mind', name: 'Mind', value: 62, delta: 2 },
    { id: 'st-body', name: 'Body', value: 58, delta: 1 },
    { id: 'st-skill', name: 'Skill', value: 45, delta: 3 },
    { id: 'st-social', name: 'Social', value: 50, delta: 0 },
    { id: 'st-fin', name: 'Finance', value: 47, delta: 1 },
  ],
  journal: [
    {
      id: 'j-2025-11-08',
      date: '2025-11-08',
      mood: 6,
      energy: 5,
      text: 'Did a little, not perfect. Proud I showed up.',
      tags: ['consistency'],
    },
  ],
  sessions: [
    {
      id: 'fs-001',
      start: '2025-11-08T09:00:00',
      end: '2025-11-08T09:25:00',
      mode: 'focus',
      bpmTarget: 90,
      notes: 'Deep work sprint',
      xp: 40,
    },
  ],
  tools: [
    {
      id: 't-kb',
      name: 'Kettlebell 20lb',
      type: 'equipment',
      link: '',
      notes: '10-min circuits',
    },
    {
      id: 't-book',
      name: 'Atomic Habits',
      type: 'book',
      link: '',
      notes: '1 chapter/week',
    },
  ],
  network: [
    {
      id: 'c-mentor',
      name: 'Mentor (Coach A.)',
      role: 'mentor',
      notes: 'Monthly check-in',
    },
  ],
  settings: {
    sessionDefaultMinutes: 25,
    showEnergyMeter: true,
    theme: 'clean-light',
    navi: {
      profile: {
        id: 'navi-001',
        name: 'Navi.EXE',
        personalityPreset: 'coach',
        skinId: 'default_core',
        currentMode: 'auto',
        enabledModes: {
          life_os: true,
          work_os: true,
          social_os: true,
          metaverse_os: true,
        },
        level: 1,
        xp: 0,
        rank: 'Companion',
        bondLevel: 1,
        affection: 0,
        loyalty: 0,
        trust: 0,
        bondTitle: 'Unlinked',
        personalityState: 'Neutral-Calm',
        unlockedFeatures: [],
        interactionCount: 0,
        avatarDescription: 'A helpful Net-Navi companion with a friendly presence',
        memoryEnabled: true,
        avatar: {
          style: 'classic',
          type: 'sparkle',
          primaryColor: '#6366f1',
          secondaryColor: '#a5b4fc',
          backgroundColor: '#eef2ff',
          shape: 'circle',
          glowEnabled: true,
        },
        coreStats: {
          logic: 5,
          creativity: 5,
          empathy: 6,
          efficiency: 5,
        },
      },
    },
  },
  leaderboard: [{ id: 'me', name: 'You', xp: 960, streak: 5 }],
  quests: [],
  archetypeEvolutions: [],
  chatHistory: [],
  customCouncilMembers: [],
  vault: [],
  dailyCheckIns: [],
  memoryItems: [],
  sessionSummaries: [],
  relationshipMemories: [],
  naviState: {
    id: 'default',
    personaName: 'Navi.EXE',
    bondLevel: 1,
    styleNotes: 'Supportive, strategic, playful when appropriate.',
    lastSessionAt: new Date().toISOString(),
    totalMessages: 0,
  },
  files: [],
  generatedImages: [],
};
